#!/bin/bash
### BEGIN INIT INFO
# Provides:          DFergus
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: self define auto start
# Description:       self define auto start
### END INIT INFO
iptables-restore < /etc/iptables.rules

exit 0
